### ISSUE TITLE
Influence of the color jittering parameters

### ISSUE THREAD

**Issue by PkuRainBow** [googleinterns/wss#1]
Great work! We find that you apply only the color jittering augmentation as the strong augmentation. So we are very interested in the influence of the choice of the color jittering parameters.

For example, the default setting in the release code is, 

https://github.com/googleinterns/wss/blob/8069dbe8b68b409a891224508f35c6ae5ecec4c9/core/preprocess_utils.py#L715-L718

According to the previous SimCLR paper, we know they set them as follows:

```
  brightness = 0.8
  contrast = 0.8
  saturation = 0.8
  hue = 0.2
```

It would be great if you could share more results of the influence on the choices of these four hyperparameters!

**Comment by Yuliang-Zou** [comment]
Hi @PkuRainBow , thanks for your interest! We have an ablation study in Figure 5(e) of the paper. 

We mainly adjust the strengths of brightness, contrast, and saturation. Using the same strength as in SimCLR leads to slightly worse performance. But a "strong enough" operation is necessary, otherwise, the model will overfit to the training set in the low-data regime. Overall, we find that 0.5 is a reasonable value.

**Comment by PkuRainBow** [comment]
@Yuliang-Zou Thanks for your explanation!
